version: '3.8'
services:
  backend:
    image: sinda12/sustainafood-backend:1.0.108
    container_name: backend
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://mohammedazizgawet:novastackers@sustainafood.ihxbt.mongodb.net/SustainaFood?retryWrites=true&w=majority&appName=SustainaFood
      - TOKEN_SECRET_KEY="mzenfmezn809097B?cvknazlkf23EE12lkdvslllcdscmazehvlczomiv"
      - FRONTEND_URL=http://localhost:5173
      - DOCKER_ENV=true
      - FLASK_BASE_URL=http://flask:5000
    env_file:
      - ./SustainaFoodBack/.env
    networks:
      - sustainafood-network

  frontend:
    image: sinda12/sustainafood-frontend:1.0.108
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8082
      - CHOKIDAR_USEPOLLING=true # Ensure file watching works in Docker
    networks:
      - sustainafood-network

  flask:
    image: sinda12/sustainafood-flask:1.0.58
    container_name: flask
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./RecommendationModel/data:/app/data
      - ./RecommendationModel/model:/app/model
    environment:
      - FLASK_APP=recommendation_api.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    networks:
      - sustainafood-network

networks:
  sustainafood-network:
    driver: bridge