version: '3.8'

services:
  backend:
    build:
      context: ./SustainaFoodBack
    container_name: backend
    ports:
      - "8082:8082"
    env_file:
      - ./SustainaFoodBack/.env
    networks:
      - sustainafood-network

  frontend:
    build:
      context: ./SustainaFoodFront
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8082
    networks:
      - sustainafood-network

  flask:
    build:
      context: ./RecommendationModel
    container_name: flask
    ports:
      - "5000:5000"
    networks:
      - sustainafood-network

networks:
  sustainafood-network:
    driver: bridge