version: '3.8'

services:
  backend:
    image: sinda12/sustainafood-backend:${VERSION:-latest}
    container_name: backend
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - FRONTEND_URL=http://localhost:5173
    networks:
      - sustainafood-network

  frontend:
    image: sinda12/sustainafood-frontend:${VERSION:-latest}
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8082
    networks:
      - sustainafood-network

  flask:
    image: sinda12/sustainafood-flask:${VERSION:-latest}
    container_name: flask
    ports:
      - "5000:5000"
    networks:
      - sustainafood-network

networks:
  sustainafood-network:
    driver: bridge