version: '3.8'
services:
  backend:
    build: ./SustainaFoodBack
    ports:
      - "8082:8082"  # Updated to match backend port
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb+srv://mohammedazizgawet:novastackers@sustainafood.ihxbt.mongodb.net/SustainaFood?retryWrites=true&w=majority&appName=SustainaFood
      # Ensure the backend environment variables are correctly configured to connect to MongoDB Atlas

  frontend:
    build: ./SustainaFoodFront
    ports:
      - "5173:5173"  # Updated to match frontend port
    depends_on:
      - backend

# Removed the MongoDB service as MongoDB Atlas is being used
volumes:
  mongodb_data: