name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install backend dependencies
        run: |
          cd ../SustainaFoodBack
          npm install

      # Run tests (if you have any)
      - name: Run backend tests
        run: |
          cd ../SustainaFoodBack
          npm test