name: Deploy Backend

on:
  push:
    branches:
      - main  # Déclencher l'action quand on push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Se connecter à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construire et pousser l'image Docker
        run: |
          docker build -t monrepo/sustainaback:latest .
          docker push monrepo/sustainaback:latest

      - name: Déployer sur le serveur
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull monrepo/sustainaback:latest
            docker stop sustaina-container || true
            docker rm sustaina-container || true
            docker run -d -p 3000:3000 --name sustaina-container monrepo/sustainaback:latest

