name: Deploy to Server

on:
  push:
    branches:
      - main  # Modifier si ta branche de déploiement est différente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérification du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Connexion à Docker Hub
      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: "nawrasse"
          password: "222jft7768"


    # Étape 3 : Construction et Tagging de l'image Docker
    - name: Build and Tag Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sustainafoodback:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/sustainafoodback:latest ${{ secrets.DOCKER_USERNAME }}/sustainafoodback:$(date +%Y%m%d%H%M)

    # Étape 4 : Push de l'image vers Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/sustainafoodback:latest

    # Étape 5 : Déploiement sur le serveur distant via SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22  # Modifier si le SSH utilise un autre port
        script: |
          echo "Déploiement en cours sur le serveur..."
          
          # Arrêt et suppression du conteneur existant s'il y en a un
          docker stop sustainafoodback || true
          docker rm sustainafoodback || true
          
          # Récupération de la nouvelle image
          docker pull ${{ secrets.DOCKER_USERNAME }}/sustainafoodback:latest
          
          # Lancement du conteneur avec les bons paramètres
          docker run -d --name sustainafoodback \
            -p 80:80 \
            --restart unless-stopped \
            ${{ secrets.DOCKER_USERNAME }}/sustainafoodback:latest

          echo "Déploiement terminé avec succès !"
