name: Deploy to Server

on:
  push:
    branches:
      - main   # ou la branche que tu utilises pour déployer, par exemple "nawrasse"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérification du code source
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Connexion à Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Étape 3 : Construction de l'image Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sustainafoodback .

    # Étape 4 : Push de l'image vers Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/sustainafoodback

    # Étape 5 : Déploiement sur le serveur distant via SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22  # Par défaut, SSH utilise le port 22
        script: |
          # Commandes pour déployer sur ton serveur
          docker pull ${{ secrets.DOCKER_USERNAME }}/sustainafoodback
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/sustainafoodback

