name: CI/CD Pipeline

on:
  push:
    branches: [main, sinda]
  pull_request:
    branches: [main]

env:
  # ⚠️ ATTENTION : Ces informations seront visibles dans les logs publics
  SONAR_HOST: "https://sonarcloud.io"
  SONAR_ORG: "chammem"
  BACKEND_KEY: "sustainafood_backend"
  FRONTEND_KEY: "sustainafood_frontend"
  SONAR_TOKEN: "4b75a0fef4c5ae5bd4b40ba192666a31aeac6853" # ⚠️ Token exposé
  DOCKER_USERNAME: "sinda12"
  DOCKER_REPO_BACKEND: "sustainafood-backend"
  DOCKER_REPO_FRONTEND: "sustainafood-frontend"

jobs:
  backend:
    name: Backend Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: SustainaFoodBack
        run: npm ci

      - name: Run tests with coverage
        working-directory: SustainaFoodBack
        run: npm run test:coverage

      - name: Create SonarCloud Project (Backend)
        run: |
          curl -X POST "$SONAR_HOST/api/projects/create" \
            -u "$SONAR_TOKEN:" \
            -d "project=$BACKEND_KEY&name=SustainaFood+Backend&organization=$SONAR_ORG" \
            || echo "Le projet existe peut-être déjà"

      - name: SonarCloud Scan (Backend)
        working-directory: SustainaFoodBack
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$BACKEND_KEY \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.scm.disabled=true

      - name: Increment Version (Backend)
        id: version
        run: |
          VERSION_FILE=SustainaFoodBack/version.txt
          if [ ! -f "$VERSION_FILE" ]; then
            echo "1.0.0" > $VERSION_FILE
          fi
          VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $NEW_VERSION > $VERSION_FILE
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit Updated Version (Backend)
        run: |
          git config user.name "chammem"
          git config user.email "chammemcinda@gmail.com"
          git pull --rebase origin $(git rev-parse --abbrev-ref HEAD) # Pull latest changes
          git add SustainaFoodBack/version.txt
          git commit -m "ci: increment backend version to $VERSION"
          git push

      - name: Log in to Docker Hub
        run: echo "cindaa123." | docker login -u "sinda12" --password-stdin

      - name: Build and Push Docker Image (Backend)
        working-directory: SustainaFoodBack
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO_BACKEND:$VERSION .
          docker push $DOCKER_USERNAME/$DOCKER_REPO_BACKEND:$VERSION

  frontend:
    name: Frontend Analysis
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: SustainaFoodFront
        run: npm ci

      - name: Run tests with coverage
        working-directory: SustainaFoodFront
        run: npm test -- --coverage --watchAll=false

      - name: Create SonarCloud Project (Frontend)
        run: |
          curl -X POST "$SONAR_HOST/api/projects/create" \
            -u "$SONAR_TOKEN:" \
            -d "project=$FRONTEND_KEY&name=SustainaFood+Frontend&organization=$SONAR_ORG" \
            || echo "Le projet existe peut-être déjà"

      - name: SonarCloud Scan (Frontend)
        working-directory: SustainaFoodFront
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$FRONTEND_KEY \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.exclusions=**/node_modules/**,**/build/** \
            -Dsonar.scm.disabled=true

      - name: Increment Version (Frontend)
        id: version
        run: |
          VERSION_FILE=SustainaFoodFront/version.txt
          if [ ! -f "$VERSION_FILE" ]; then
            echo "1.0.0" > $VERSION_FILE
          fi
          VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $NEW_VERSION > $VERSION_FILE
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit Updated Version (Frontend)
        run: |
          git config user.name "chammem"
          git config user.email "chammemcinda@gmail.com"
          git pull --rebase origin $(git rev-parse --abbrev-ref HEAD) # Pull latest changes
          git add SustainaFoodFront/version.txt
          git commit -m "ci: increment frontend version to $VERSION"
          git push

      - name: Log in to Docker Hub
        run: echo "cindaa123." | docker login -u "sinda12" --password-stdin

      - name: Build and Push Docker Image (Frontend)
        working-directory: SustainaFoodFront
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO_FRONTEND:$VERSION .
          docker push $DOCKER_USERNAME/$DOCKER_REPO_FRONTEND:$VERSION