name: CI/CD Pipeline

on:
  push:
    branches: [main, sinda]
  pull_request:
    branches: [main]

env:
  # ⚠️ ATTENTION : Ces informations seront visibles dans les logs publics
  SONAR_HOST: "https://sonarcloud.io"
  SONAR_ORG: "chammem"
  BACKEND_KEY: "sustainafood_backend"
  FRONTEND_KEY: "sustainafood_frontend"
  SONAR_TOKEN: "4b75a0fef4c5ae5bd4b40ba192666a31aeac6853" # ⚠️ Token exposé
  DOCKER_USERNAME: "sinda12"
  DOCKER_REPO_BACKEND: "sustainafood-backend"
  DOCKER_REPO_FRONTEND: "sustainafood-frontend"
  DOCKER_REPO_FLASK: "sustainafood-flask"
  NEXUS_URL: "2dfc-197-20-41-204.ngrok-free.app"  # Sans https://
  NEXUS_PORT: "8082"                              # Doit matcher Nexus
  NEXUS_REPO: "docker-hosted"
jobs:
  versioning:
    name: Increment Shared Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Out Target Branch
        run: |
          git fetch origin sinda
          git checkout sinda

      - name: Get Current Version
        id: set-version
        run: |
          VERSION_FILE=shared-version.txt
          if [ ! -f "$VERSION_FILE" ]; then
            echo "1.0.0" > $VERSION_FILE
          fi
          VERSION=$(cat $VERSION_FILE)
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Display Version
        run: echo "Using version ${{ steps.set-version.outputs.version }}"

  backend:
    name: Backend Analysis
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Latest Changes
        run: git fetch origin

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: SustainaFoodBack
        run: npm install --force

      - name: Run tests with coverage
        working-directory: SustainaFoodBack
        run: npm run test:coverage

      - name: Create SonarCloud Project (Backend)
        run: |
          curl -X POST "$SONAR_HOST/api/projects/create" \
            -u "$SONAR_TOKEN:" \
            -d "project=$BACKEND_KEY&name=SustainaFood+Backend&organization=$SONAR_ORG" \
            || echo "Le projet existe peut-être déjà"

      - name: SonarCloud Scan (Backend)
        working-directory: SustainaFoodBack
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$BACKEND_KEY \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.scm.disabled=true

      - name: Log in to Docker Hub
        run: echo "cindaa123." | docker login -u "sinda12" --password-stdin

      - name: Build and Push Docker Image (Backend)
        working-directory: SustainaFoodBack
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO_BACKEND:${{ needs.versioning.outputs.version }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO_BACKEND:${{ needs.versioning.outputs.version }}

  frontend:
    name: Frontend Analysis
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Latest Changes
        run: git fetch origin

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: SustainaFoodFront
        run: npm install --force

      - name: Run tests with coverage
        working-directory: SustainaFoodFront
        run: npm test -- --coverage --watchAll=false

      - name: Create SonarCloud Project (Frontend)
        run: |
          curl -X POST "$SONAR_HOST/api/projects/create" \
            -u "$SONAR_TOKEN:" \
            -d "project=$FRONTEND_KEY&name=SustainaFood+Frontend&organization=$SONAR_ORG" \
            || echo "Le projet existe peut-être déjà"

      - name: SonarCloud Scan (Frontend)
        working-directory: SustainaFoodFront
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$FRONTEND_KEY \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.exclusions=**/node_modules/**,**/build/** \
            -Dsonar.scm.disabled=true

      - name: Log in to Docker Hub
        run: echo "cindaa123." | docker login -u "sinda12" --password-stdin

      - name: Build and Push Docker Image (Frontend)
        working-directory: SustainaFoodFront
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO_FRONTEND:${{ needs.versioning.outputs.version }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO_FRONTEND:${{ needs.versioning.outputs.version }}

  flask:
    name: Flask Service Build and Push
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        run: echo "cindaa123." | docker login -u "sinda12" --password-stdin

      - name: Build and Push Docker Image (Flask)
        working-directory: RecommendationModel
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO_FLASK:${{ needs.versioning.outputs.version }} .
          docker push $DOCKER_USERNAME/$DOCKER_REPO_FLASK:${{ needs.versioning.outputs.version }}

  nexus_push:
    needs: [backend, frontend, flask]
    runs-on: ubuntu-latest
    steps:
      - name: Configure Docker for Nexus
        run: |
          # Autorise les connexions non sécurisées (http)
          echo '{ "insecure-registries": ["'${{ env.NEXUS_URL }}:${{ env.NEXUS_PORT }}'"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Nexus
        run: |
          # Adding hardcoded credentials since secrets aren't used
          echo "c40eebf3-c9c0-405b-8334-fc9201a626bf" | docker login \
            -u "admin" \
            --password-stdin \
            ${{ env.NEXUS_URL }}:${{ env.NEXUS_PORT }}

      - name: Pull Images from Docker Hub
        run: |
          VERSION="${{ needs.versioning.outputs.version }}"
          # Log in to Docker Hub
          echo "cindaa123." | docker login -u "$DOCKER_USERNAME" --password-stdin
          
          # Pull images from Docker Hub
          for APP in backend frontend flask; do
            echo "Pulling sustainafood-$APP:$VERSION from Docker Hub"
            docker pull $DOCKER_USERNAME/sustainafood-$APP:$VERSION
          done
        
      - name: Check Nexus Connectivity
        id: nexus-check
        continue-on-error: true
        run: |
          # Test connectivity to Nexus before attempting login
          echo "Testing connectivity to Nexus server..."
          curl --connect-timeout 10 -v http://${{ env.NEXUS_URL }}:${{ env.NEXUS_PORT }}/v2/ || echo "Cannot connect to Nexus Docker registry"
          
          # Try different URL formats
          curl --connect-timeout 10 -v http://${{ env.NEXUS_URL }}/v2/ || echo "Cannot connect without port"
          curl --connect-timeout 10 -v https://${{ env.NEXUS_URL }}/v2/ || echo "Cannot connect with HTTPS"
          
          # Check general nexus server connectivity
          curl --connect-timeout 10 -v https://${{ env.NEXUS_URL }} || echo "Cannot connect to base Nexus URL"
          
          echo "::set-output name=status::checked"
      
      - name: Try Alternative Docker Login
        id: nexus-login
        continue-on-error: true
        run: |
          # Try login with less strict settings
          echo "c40eebf3-c9c0-405b-8334-fc9201a626bf" | docker login --insecure -u "admin" --password-stdin ${{ env.NEXUS_URL }}:${{ env.NEXUS_PORT }} || echo "Login failed"
          echo "::set-output name=status::attempted"
      
      - name: Tag Images for Nexus
        run: |
          VERSION="${{ needs.versioning.outputs.version }}"
          
          for APP in backend frontend flask; do
            echo "Tagging sustainafood-$APP:$VERSION for Nexus"
            docker tag $DOCKER_USERNAME/sustainafood-$APP:$VERSION \
              ${{ env.NEXUS_URL }}:${{ env.NEXUS_PORT }}/${{ env.NEXUS_REPO }}/sustainafood-$APP:$VERSION
          done
      
      - name: Attempt to Push Images to Nexus
        continue-on-error: true
        run: |
          VERSION="${{ needs.versioning.outputs.version }}"
          
          # Try to push with insecure flag
          for APP in backend frontend flask; do
            echo "Attempting to push sustainafood-$APP:$VERSION to Nexus"
            docker push --insecure ${{ env.NEXUS_URL }}:${{ env.NEXUS_PORT }}/${{ env.NEXUS_REPO }}/sustainafood-$APP:$VERSION || echo "Push failed for $APP"
          done
          
          echo "Note: If pushes failed, check Nexus server connectivity and configuration."
          
      - name: Manual Deployment Instructions
        run: |
          VERSION="${{ needs.versioning.outputs.version }}"
          echo "============== MANUAL DEPLOYMENT INSTRUCTIONS =============="
          echo "The images are available on Docker Hub and can be manually pushed to Nexus:"
          echo ""
          echo "1. Login to Docker Hub:"
          echo "   docker login -u sinda12"
          echo ""
          echo "2. Pull the images:"
          for APP in backend frontend flask; do
            echo "   docker pull sinda12/sustainafood-$APP:$VERSION"
          done
          echo ""
          echo "3. Tag for Nexus:"
          for APP in backend frontend flask; do
            echo "   docker tag sinda12/sustainafood-$APP:$VERSION ${NEXUS_URL}:${NEXUS_PORT}/${NEXUS_REPO}/sustainafood-$APP:$VERSION"
          done
          echo ""
          echo "4. Login to Nexus (using your Nexus credentials):"
          echo "   docker login ${NEXUS_URL}:${NEXUS_PORT}"
          echo ""
          echo "5. Push to Nexus:"
          for APP in backend frontend flask; do
            echo "   docker push ${NEXUS_URL}:${NEXUS_PORT}/${NEXUS_REPO}/sustainafood-$APP:$VERSION"
          done
          echo ""
          echo "============================================================"
          echo "The workflow has completed successfully even if Nexus push failed."
          echo "Images are available on Docker Hub for deployment."