name: CI/CD Pipeline

on:
  push:
    branches: [main, sinda]
  pull_request:
    branches: [main]

env:
  # ⚠️ Attention: Ces informations seront visibles dans les logs publics
  SONAR_HOST: "https://sonarcloud.io"
  SONAR_ORG: "chammem"
  BACKEND_KEY: "sustainafood_backend"
  FRONTEND_KEY: "sustainafood_frontend"
  # ⚠️ Token en clair - extrêmement risqué
  SONAR_TOKEN: "4b75a0fef4c5ae5bd4b40ba192666a31aeac6853" 

jobs:
  backend:
    name: Backend Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: SustainaFoodBack
        run: npm ci

      - name: Run tests with coverage
        working-directory: SustainaFoodBack
        run: npm run test:coverage

      - name: SonarCloud Scan
        working-directory: SustainaFoodBack
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$BACKEND_KEY \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  frontend:
    name: Frontend Analysis
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: SustainaFoodFront
        run: npm ci

      - name: Run tests with coverage
        working-directory: SustainaFoodFront
        run: npm test -- --coverage --watchAll=false

      - name: SonarCloud Scan
        working-directory: SustainaFoodFront
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=$SONAR_ORG \
            -Dsonar.projectKey=$FRONTEND_KEY \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.exclusions=**/node_modules/**,**/build/**