name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - sinda
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build, Test, and SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: SustainaFoodBack/package-lock.json

      - name: Install dependencies (Backend)
        run: |
          cd SustainaFoodBack
          npm ci

      - name: Run tests with coverage (Backend)
        run: |
          cd SustainaFoodBack
          npm run test:coverage

      - name: Run SonarQube analysis (Backend)
        env:
          SONAR_TOKEN: sqa_e70c9f3c89d643fa9db70bffcbee28ce879c2ac4
        run: |
          sonar-scanner \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN

  frontend:
    needs: backend
    name: Frontend Build, Test, and SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: SustainaFoodFront/package-lock.json

      - name: Install dependencies (Frontend)
        run: |
          cd SustainaFoodFront
          npm ci

      - name: Build Project (Frontend)
        run: |
          cd SustainaFoodFront
          npm run build

      - name: Run tests (Frontend)
        run: |
          cd SustainaFoodFront
          npm test

      - name: Run SonarQube analysis (Frontend)
        env:
          SONAR_TOKEN: sqa_e70c9f3c89d643fa9db70bffcbee28ce879c2ac4
        run: |
          cd SustainaFoodFront
          sonar-scanner \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN