name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - sinda
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build, Test, and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: SustainaFoodBack/package-lock.json

      - name: Install dependencies (Backend)
        run: |
          cd SustainaFoodBack
          npm ci

      - name: Run tests with coverage (Backend)
        run: |
          cd SustainaFoodBack
          npm run test:coverage

      - name: Run SonarCloud analysis (Backend)
        env:
          SONAR_TOKEN: 80a158098efce80c33201f4b2a8a77d05b87f8e2
        run: |
          cd SustainaFoodBack
          npm run sonar -- -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=your_organization_key \
            -Dsonar.projectKey=sustainafood_backend

  frontend:
    needs: backend
    name: Frontend Build, Test, and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: SustainaFoodFront/package-lock.json

      - name: Install dependencies (Frontend)
        run: |
          cd SustainaFoodFront
          npm ci

      - name: Build Project (Frontend)
        run: |
          cd SustainaFoodFront
          npm run build

      - name: Run tests (Frontend)
        run: |
          cd SustainaFoodFront
          npm test -- --coverage --watchAll=false

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarCloud analysis (Frontend)
        env:
          SONAR_TOKEN: 80a158098efce80c33201f4b2a8a77d05b87f8e2
        run: |
          cd SustainaFoodFront
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.projectKey=sustainafood_frontend \
            -Dsonar.organization=your_organization_key \
            -Dsonar.sources=src \
            -Dsonar.exclusions=**/node_modules/**,**/build/** \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info