name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - sinda
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build, Test, and SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: SustainaFoodBack/package-lock.json

      - name: Install dependencies (Backend)
        run: |
          cd SustainaFoodBack
          npm ci

      - name: Run tests with coverage (Backend)
        run: |
          cd SustainaFoodBack
          npm run test:coverage

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube analysis (Backend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd SustainaFoodBack
          sonar-scanner \
            -Dsonar.host.url=http://172.20.119.237:9000 \ # Updated with your machine's IP
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.projectKey=sustainafood_backend \
            -Dsonar.sources=src \
            -Dsonar.tests=tests \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  frontend:
    needs: backend
    name: Frontend Build, Test, and SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: SustainaFoodFront/package-lock.json

      - name: Install dependencies (Frontend)
        run: |
          cd SustainaFoodFront
          npm ci

      - name: Build Project (Frontend)
        run: |
          cd SustainaFoodFront
          npm run build

      - name: Run tests (Frontend)
        run: |
          cd SustainaFoodFront
          npm test -- --coverage --watchAll=false

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube analysis (Frontend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd SustainaFoodFront
          sonar-scanner \
            -Dsonar.host.url=http://172.20.119.237:9000 \ # Updated with your machine's IP
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.projectKey=sustainafood_frontend \
            -Dsonar.sources=src \
            -Dsonar.exclusions=**/node_modules/**,**/build/** \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info